import "../styles/globals.scss";
import Head from "next/head";
import Nav from "../components/shared/nav";
import Footer from "../components/shared/footer";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Open Blimp</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
